---
- name: Set up environmental variables
  template:
    src: '{{ playbook_dir }}/templates/.env.template'
    dest: '{{ ansistrano_release_path.stdout }}/.env'

- name: Install Composer dependencies
  composer:
    command: install
    working_dir: '{{ ansistrano_release_path.stdout }}'

- name: Run migrations
  command: "{{ artisan_path }} migrate"

#- name: Install Node dependencies
#  community.general.npm:
#    path: '{{ ansistrano_release_path.stdout }}'
#    executable: '/home/qrazi/.nvm/versions/node/v12.18.4/bin/npm'
#    production: yes
#
#- name: Install Node dependencies
#  command: /home/qrazi/.nvm/versions/node/v12.18.4/bin/npm install
#  args:
#    chdir: '{{ ansistrano_release_path.stdout }}'
#
#
#- name: Run WebPack
#  command: /home/qrazi/.nvm/versions/node/v12.18.4/bin/npm run production
#  args:
#    chdir: '{{ ansistrano_release_path.stdout }}'

#- name: Set permissions and ownership
#  become: yes
#  file:
#    path: '{{ ansistrano_release_path.stdout }}/{{ item }}'
#    owner: 'www-data'
#    group: 'www-data'
#    state: 'directory'
#    recurse: 'yes'
#  with_items:
#    - storage
#    - web/cpresources
#    - web/uploads

