---
- name: Deploy to server

  hosts: test

  vars_files:
    - ./vars/deploy_vault.yml
    - ./vars/deploy_vars.yml

#  environment:
#    TMPDIR: "{{ ansible_env.HOME }}/tmp"
#    TMP: "{{ ansible_env.HOME }}/tmp"

  vars:
    # App vars
    artisan_path: "{{ ansistrano_release_path.stdout }}/craft"

    ##########
    # Ansistrano vars
    ##########

    # Arrays of directories and files to be shared.
    # The following arrays of directories and files will be symlinked to the current release directory after the 'update-code' step and its callbacks
    # Notes:
    # * Paths are relative to the /shared directory (no starting /)
    # * If your items are in a subdirectory, write the entire path to each shared directory
    #
    # Example:
    # ansistrano_shared_paths:
    #   - path/to/first-dir
    #   - path/next-dir
    # ansistrano_shared_files:
    #   - my-file.txt
    #   - path/to/file.txt
    ansistrano_shared_paths:
      - storage

    # Deploy strategy git
    ansistrano_deploy_via: git
    ansistrano_git_repo: "git@github.com:Sjos12/Remote_homework.git"
    ansistrano_git_branch: "{{ deploy_branch }}"
    ansistrano_deploy_to: "{{ deploy_dir }}"
    ansistrano_keep_releases: 3

    # Hooks: custom tasks if you need them
    ansistrano_after_symlink_shared_tasks_file: "{{ playbook_dir }}/tasks/after-symlink-shared.yml"
    ansistrano_before_cleanup_tasks_file: "{{ playbook_dir }}/tasks/before-cleanup.yml"

    # Ansible vars
    ansible_ssh_user: qrazi

  roles:
    - ansistrano.deploy
