---
all:
  children:
    local:
      hosts:
        127.0.0.1 ansible_connection=local
    test:
      hosts:
        167.71.1.93:
      vars:
        ansistrano_deploy_via: git # Method used to deliver the code to the server. Options are copy, rsync, git, svn, s3 or download
        ansible_ssh_user: qrazi
        ansible_python_interpreter: "/usr/bin/python3" # Default Ansible looks for /usr/bin/python (python2), but Ubuntu 20.04 is Python 3 by default
