---
all:
  children:
    test:
      hosts:
        167.71.1.93:
      vars:
        deploy_branch: "main"
        deploy_dir: "/var/www/test.remotehomework"
        ansible_ssh_user: qrazi
        ansible_become_password: "{{ vault_ansible_become_password }}"
        ansible_python_interpreter: "/usr/bin/python3" # Default Ansible looks for /usr/bin/python (python2), but Ubuntu 20.04 is Python 3 by default
