#
# Describe all the dependencies of the Ansible setup.
# Install all dependencies in one go with
# `ansible-galaxy install -r requirements.yml`
#
- src: ansistrano.deploy
  version: 3.6.0
- src: ansistrano.rollback
  version: 3.0.0
